server:
  port: 8085
spring:
  datasource:
    url: "jdbc:h2:mem:mahdiyar"
    username: "test_username"
    password: "test_password"
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    open-in-view: false